package tech.certgate.securityevent;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;

/**
 * A Security Event the Gateway generated and durably queued in its own SQLite
 * Outbox before sending here (docs/architecture.md, docs/data-model.md).
 * {@code id} is the Gateway-assigned event id, not generated by this DB — its
 * Unique constraint is what makes resubmission after a lost response idempotent.
 */
@Entity
@Table(name = "security_event")
public class SecurityEvent {

	@Id
	private UUID id;

	@Column(name = "occurred_at", nullable = false)
	private Instant occurredAt;

	@Column(nullable = false)
	private String type;

	@Column(nullable = false)
	private String severity;

	@Column(name = "device_id")
	private UUID deviceId;

	@Column(name = "certificate_serial")
	private String certificateSerial;

	@Column(name = "http_method")
	private String httpMethod;

	@Column(name = "request_path")
	private String requestPath;

	@Column(nullable = false)
	private String decision;

	@Column(name = "reason_code", nullable = false)
	private String reasonCode;

	@Column(name = "client_ip")
	private String clientIp;

	@Column(name = "latency_ms")
	private Integer latencyMs;

	@Column(name = "trace_id", nullable = false)
	private String traceId;

	@Column(name = "created_at", nullable = false)
	private Instant createdAt;

	protected SecurityEvent() {
	}

	public SecurityEvent(
			UUID id, Instant occurredAt, String type, String severity, UUID deviceId, String certificateSerial,
			String httpMethod, String requestPath, String decision, String reasonCode, String clientIp,
			Integer latencyMs, String traceId, Instant createdAt) {
		this.id = id;
		this.occurredAt = occurredAt;
		this.type = type;
		this.severity = severity;
		this.deviceId = deviceId;
		this.certificateSerial = certificateSerial;
		this.httpMethod = httpMethod;
		this.requestPath = requestPath;
		this.decision = decision;
		this.reasonCode = reasonCode;
		this.clientIp = clientIp;
		this.latencyMs = latencyMs;
		this.traceId = traceId;
		this.createdAt = createdAt;
	}

	public UUID getId() {
		return id;
	}
}
